// Code generated by "stringer -type=DevType"; DO NOT EDIT.

package devtype

import "strconv"

const _DevType_name = "UserRelated"

var _DevType_index = [...]uint8{0, 11}

func (i DevType) String() string {
	if i < 0 || i >= DevType(len(_DevType_index)-1) {
		return "DevType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DevType_name[_DevType_index[i]:_DevType_index[i+1]]
}
