// Code generated by "stringer -type=SleepState"; DO NOT EDIT.

package sleepstate

import "strconv"

const _SleepState_name = "Awake"

var _SleepState_index = [...]uint8{0, 5}

func (i SleepState) String() string {
	if i < 0 || i >= SleepState(len(_SleepState_index)-1) {
		return "SleepState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SleepState_name[_SleepState_index[i]:_SleepState_index[i+1]]
}
