// Code generated by "stringer -type=MeasType"; DO NOT EDIT.

package meastype

import "strconv"

const _MeasType_name = "Weight"

var _MeasType_index = [...]uint8{0, 6}

func (i MeasType) String() string {
	i -= 1
	if i < 0 || i >= MeasType(len(_MeasType_index)-1) {
		return "MeasType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MeasType_name[_MeasType_index[i]:_MeasType_index[i+1]]
}
