// Code generated by "stringer -type=Status"; DO NOT EDIT.

package status

import "strconv"

const _Status_name = "OperationWasSuccessfulTheUserIDProvidedIsAbsentOrIncorrectTheProvidedUserIDAndOrOauthCredsDoNotMatchTokenIsInvalidOrDoesntExistNoSuchSubscriptionNoSuchSubscriptionCouldBeDeletedCommentAbsentOrIncorrectTooManyNotificationsSetUserIsDeactiviatedSignatureIsInvalidWrongNotificationCallbackURLTooManyRequetsWrongActionOrWrongWebserviceUnknonwErrorServiceNotDefined"

var _Status_map = map[Status]string{
	0:    _Status_name[0:22],
	247:  _Status_name[22:58],
	250:  _Status_name[58:100],
	283:  _Status_name[100:127],
	286:  _Status_name[127:145],
	294:  _Status_name[145:177],
	304:  _Status_name[177:201],
	305:  _Status_name[201:224],
	328:  _Status_name[224:242],
	342:  _Status_name[242:260],
	343:  _Status_name[260:288],
	601:  _Status_name[288:302],
	2554: _Status_name[302:330],
	2555: _Status_name[330:342],
	2556: _Status_name[342:359],
}

func (i Status) String() string {
	if str, ok := _Status_map[i]; ok {
		return str
	}
	return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
}
